# Generated by Django 5.2.2 on 2025-06-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('decription', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
