from movies.serializers.movie import MovieSerializer as MovieSerializer
from movies.serializers.age_rating import AgeRatingSerializer as AgeRatingSerializer
from movies.serializers.movie import MovieSerializerExtend as MovieSerializerExtend
from movies.serializers.movie import MovieDetailSerializerExtend as MovieDetailSerializerExtend
